### ISSUE TITLE
Project does not compile on OS X

### ISSUE THREAD

**Issue by rcritt** [cloudflare/lua-resty-json#2]
On Mac OSX I get the following error on “make all".

******
scaner.c:49:24: error: use of undeclared identifier 'uint'
     token_predict[(uint)np[idx]] = TT_FP;
                    ^
scaner.c:49:29: error: expected ']'
     token_predict[(uint)np[idx]] = TT_FP;
                         ^
scaner.c:49:22: note: to match this '['
     token_predict[(uint)np[idx]] = TT_FP;
                  ^
scaner.c:55:24: error: use of undeclared identifier 'uint'
     token_predict[(uint)bp[idx]] = TT_BOOL;
                    ^
scaner.c:55:29: error: expected ']'
     token_predict[(uint)bp[idx]] = TT_BOOL;
                         ^
scaner.c:55:22: note: to match this '['
     token_predict[(uint)bp[idx]] = TT_BOOL;
                  ^
6 warnings and 4 errors generated.
******

To get around that on scaner.c I added the following.

******
include <sys/types.h>
******

I also removed rpath in the make file so demo and the library were created.  The same sort of thing did not work out for me in the tests directory.

**Comment by yangshuxin** [comment]
Thank you for reporting this problem. It is fixed now. On Linux, uint is defined in stdlib.h; that is why we don't building problem on Linux.

It's actually my typo. It is supposed to be cast to uint8_t.

As of I write this comment, we can build and test the lua-resty-json on OSX. The OSX I'm using to fix these problems is:
 .  "uname -a" gives Darwin shuxins-imac-2 13.1.0 Darwin Kernel Version 13.1.0: Wed Apr  2 23:52:02 PDT 2014; root:xnu-2422.92.1~2/RELEASE_X86_64 x86_64, and
 "cc -v" gives "Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)"
