### ISSUE TITLE
How to encode in lua-resty-json?

### ISSUE THREAD

**Issue by rcritt** [cloudflare/lua-resty-json#3]
All the examples I see for this project are for decoding JSON.

Do we need to use CJSON to encode when we want to return JSON strings?

**Comment by yangshuxin** [comment]
We don't have encoder for now. It is on my TODO list. You can whatever encoder you like. @agentzh has a nice encoder (in lua) in his openresty suite. I will ask him if he is wiling to contribute the lua script to this project. I will keep this issue open until I can give you a definite answer.

**Comment by bungle** [comment]
Where is the @agentzh's JSON encoder? I though that Lua cJSON (nothing to do with @agentzh: https://github.com/mpx/lua-cjson/) is the "official" encoder/decoder in OpenResty (the only one bundled in OpenResty). I did a quick search, but I didn't find the Lua script.

**Comment by agentzh** [comment]
@bungle It's just for testing and not tuned for performance. It's named ljson.lua: https://github.com/openresty/lua-nginx-module/blob/master/t/lib/ljson.lua

**Comment by bungle** [comment]
Oh, I have missed this totally, :-). Thanks for letting me know about it.
