### ISSUE TITLE
how to encode  

### ISSUE THREAD

**Issue by onlynishant** [cloudflare/lua-resty-json#9]
I have gone through examples but couldn't find any API/function for JSON encoding. Please guide me.

I tried `instance:get_strings(body)` but got error: 

` lua-resty-json/json_decoder.lua:326: bad argument #2 to 'jp_parse' (cannot convert 'table' to 'const char *')`

**Comment by jdesgats** [comment]
There is no encoding API, this library is focused on JSON parsing only at the moment.

**Comment by jdesgats** [comment]
If you want a general purpose JSON library, I suggest https://github.com/openresty/lua-cjson that is already bundled with OpenResty.
